// The exported C ABI intentionally keeps safe `extern "C"` entry points for
// source compatibility with the existing headers. Pointer validity is checked
// at each boundary; Clippy cannot express that contract. Several model APIs
// also mirror fixed EMANE call signatures and wire-cache shapes.
#![allow(
    clippy::not_unsafe_ptr_arg_deref,
    clippy::missing_safety_doc,
    clippy::too_many_arguments,
    clippy::type_complexity
)]

pub mod application_runtime;
pub mod build_id_service;
pub mod common;
pub mod control_port;
pub mod event_service;
pub mod events;
pub mod file_descriptor_service;
pub mod flow_control_manager;
pub mod native_configuration;
pub mod neighbor_metric_manager;
pub mod nem_manager;
pub mod ota_manager;
pub mod pcr_manager;
pub mod queue_metric_manager;
pub mod regex;
pub mod rf_signal_table;
pub mod statistics;
pub mod tdma_message;
pub mod xml;

// Include the protobuf modules generated by prost-build in build.rs.

pub mod protobufs {
    pub mod emane_message {
        include!(concat!(env!("OUT_DIR"), "/emane_message.rs"));
        include!(concat!(env!("OUT_DIR"), "/emane_event_message.rs"));
    }
    pub mod emane_remote_control_port_api {
        include!(concat!(
            env!("OUT_DIR"),
            "/emane_remote_control_port_api.rs"
        ));
    }
}

/// Calculates the Two-Ray pathloss.
#[no_mangle]
pub extern "C" fn emane_rs_tworay_pathloss(
    d_distance: f64,
    d_local_alt: f64,
    d_remote_alt: f64,
) -> f64 {
    if d_distance == 0.0 {
        return 0.0;
    }

    let local_alt = if d_local_alt < 1.0 { 1.0 } else { d_local_alt };
    let remote_alt = if d_remote_alt < 1.0 {
        1.0
    } else {
        d_remote_alt
    };

    let pathloss = (40.0 * d_distance.log10()) - (20.0 * (local_alt.log10() + remote_alt.log10()));

    if pathloss < 0.0 {
        0.0
    } else {
        pathloss
    }
}

/// Calculates the FreeSpace pathloss for a single frequency.
#[no_mangle]
pub extern "C" fn emane_rs_freespace_pathloss_single(d_distance: f64, freq_hz: f64) -> f64 {
    const FSPL_CONST: f64 = 41.916_900_439_033_64;
    if d_distance == 0.0 {
        return 0.0;
    }
    let val = 20.0 * (FSPL_CONST * (freq_hz / 1000000.0) * (d_distance / 1000.0)).log10();
    if val < 0.0 {
        0.0
    } else {
        val
    }
}

/// Stateful Lognormal Fading Algorithm
use rand::rngs::StdRng;
use rand::SeedableRng;
use rand_distr::{Distribution, LogNormal, Normal};

#[repr(C)]
pub struct LognormalFadingParameters {
    pub dmu: f64,
    pub dsigma: f64,
    pub dlthresh: f64,
    pub maxpathloss: f64,
    pub duthresh: f64,
    pub minpathloss: f64,
    pub lmean: f64,
    pub lstddev: f64,
    pub counter: u32,
}

pub struct LognormalFadingState {
    param_counter: u32,
    reset: bool,
    depth_dbm: f64,
    nexttime_microsec: u64,
    rng: StdRng,
}

impl Default for LognormalFadingState {
    fn default() -> Self {
        Self::new()
    }
}

impl LognormalFadingState {
    pub fn new() -> Self {
        Self {
            param_counter: 0,
            reset: true,
            depth_dbm: 0.0,
            nexttime_microsec: 0,
            rng: StdRng::seed_from_u64(5489),
        }
    }

    pub fn process(
        &mut self,
        power_dbm: f64,
        params: &LognormalFadingParameters,
        now_microsec: u64,
    ) -> Option<f64> {
        if !power_dbm.is_finite()
            || !params.dmu.is_finite()
            || !params.dsigma.is_finite()
            || params.dsigma < 0.0
            || !params.lmean.is_finite()
            || !params.lstddev.is_finite()
            || params.lmean < 0.0
            || params.lstddev < 0.0
            || params.dlthresh > params.duthresh
            || params.minpathloss >= params.maxpathloss
        {
            return None;
        }

        if params.counter != self.param_counter {
            self.reset = true;
            self.param_counter = params.counter;
        }

        if self.reset || now_microsec >= self.nexttime_microsec {
            let length_seconds = if params.lstddev == 0.0 {
                params.lmean
            } else {
                Normal::new(params.lmean, params.lstddev)
                    .ok()?
                    .sample(&mut self.rng)
                    .max(0.0)
            };
            let length_microseconds = (length_seconds * 1_000_000.0)
                .round()
                .clamp(0.0, u64::MAX as f64) as u64;
            self.nexttime_microsec = now_microsec.saturating_add(length_microseconds);

            let depth_norm = if params.dsigma == 0.0 {
                params.dmu.exp()
            } else {
                LogNormal::new(params.dmu, params.dsigma)
                    .ok()?
                    .sample(&mut self.rng)
            };

            self.depth_dbm = if depth_norm <= params.dlthresh {
                params.maxpathloss
            } else if depth_norm >= params.duthresh || params.duthresh == params.dlthresh {
                params.minpathloss
            } else {
                ((depth_norm - params.dlthresh) / (params.duthresh - params.dlthresh))
                    * (params.minpathloss - params.maxpathloss)
                    + params.maxpathloss
            };
            self.reset = false;
        }

        Some(10.0_f64.powf((power_dbm - self.depth_dbm) / 10.0))
    }
}

#[no_mangle]
pub extern "C" fn emane_rs_lognormal_fading_new() -> *mut LognormalFadingState {
    Box::into_raw(Box::new(LognormalFadingState::new()))
}

#[no_mangle]
pub extern "C" fn emane_rs_lognormal_fading_free(state: *mut LognormalFadingState) {
    if !state.is_null() {
        unsafe {
            drop(Box::from_raw(state));
        }
    }
}

#[no_mangle]
pub extern "C" fn emane_rs_lognormal_fading_process(
    state_ptr: *mut LognormalFadingState,
    power_dbm: f64,
    params: *const LognormalFadingParameters,
    now_microsec: u64,
) -> f64 {
    if state_ptr.is_null() || params.is_null() {
        return 0.0; // Fallback
    }

    let state = unsafe { &mut *state_ptr };
    let p = unsafe { &*params };

    state.process(power_dbm, p, now_microsec).unwrap_or(0.0)
}
pub mod antenna;
pub mod flow_control_client;
pub mod formatters;
pub mod log_service;
pub mod nakagami_fading_algorithm;
pub mod nem_queued_layer;
pub mod noise_recorder;
pub mod spectral_mask;
pub mod spectrum_window_utils;
pub mod timer_service;

#[no_mangle]
pub extern "C" fn emane_rs_socket_close(sock: libc::c_int) -> libc::c_int {
    if sock != -1 {
        unsafe {
            libc::close(sock);
        }
    }
    -1
}

#[no_mangle]
pub extern "C" fn emane_rs_socket_sendto(
    sock: libc::c_int,
    buf: *const libc::c_void,
    len: libc::size_t,
    flags: libc::c_int,
    addr: *const libc::sockaddr,
    addrlen: libc::socklen_t,
) -> libc::ssize_t {
    unsafe { libc::sendto(sock, buf, len, flags, addr, addrlen) }
}
pub mod boundary_message_manager;
pub mod spectrum_monitor;

pub mod agents;
pub mod generators;
pub mod plugin_interface;
pub mod raw_transport;
pub mod types;
pub mod r#virtual;
pub mod xml_parser;
