
[workspace]
resolver = "2"
members = [
    "rust/emane-plugin-api",
    "rust/emane-core",
    "rust/plugins/dummy-mac",
    "rust/plugins/ieee80211abg",
    "rust/plugins/bentpipe",
    "rust/plugins/tdma",
    "rust/plugins/rfpipe",
    "rust/plugins/bypass-mac",
    "rust/plugins/bypass-phy",
    "rust/plugins/commeffect-shim",
    "rust/plugins/timing-analysis-shim",
    "rust/plugins/phy-api-test-shim",
]
